services:
  - type: web
    name: innocence-api
    env: python
    buildCommand: "pip install -r requirements.txt && python -m spacy download en_core_web_sm && python download_model.py"
    startCommand: "uvicorn app.main_bert:app --host 0.0.0.0 --port $PORT"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"